// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TaskBoard.Data;

#nullable disable

namespace TaskBoard.Migrations
{
    [DbContext(typeof(TaskBoardContext))]
    partial class TaskBoardContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TaskBoard.Models.Board", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Boards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 2, 4, 18, 23, 16, 312, DateTimeKind.Utc).AddTicks(236),
                            Description = "Main project board",
                            Name = "Project Alpha",
                            UpdatedAt = new DateTime(2026, 2, 4, 18, 23, 16, 312, DateTimeKind.Utc).AddTicks(236)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 2, 4, 18, 23, 16, 312, DateTimeKind.Utc).AddTicks(239),
                            Description = "Secondary project",
                            Name = "Project Beta",
                            UpdatedAt = new DateTime(2026, 2, 4, 18, 23, 16, 312, DateTimeKind.Utc).AddTicks(239)
                        });
                });

            modelBuilder.Entity("TaskBoard.Models.TaskItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BoardId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BoardId");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BoardId = 1,
                            CreatedAt = new DateTime(2026, 2, 4, 18, 23, 16, 312, DateTimeKind.Utc).AddTicks(442),
                            Description = "Initialize database schema",
                            Priority = 2,
                            Status = 2,
                            Title = "Setup Database",
                            UpdatedAt = new DateTime(2026, 2, 4, 18, 23, 16, 312, DateTimeKind.Utc).AddTicks(443)
                        },
                        new
                        {
                            Id = 2,
                            BoardId = 1,
                            CreatedAt = new DateTime(2026, 2, 4, 18, 23, 16, 312, DateTimeKind.Utc).AddTicks(446),
                            Description = "Build REST API",
                            Priority = 2,
                            Status = 1,
                            Title = "Create API Endpoints",
                            UpdatedAt = new DateTime(2026, 2, 4, 18, 23, 16, 312, DateTimeKind.Utc).AddTicks(446)
                        },
                        new
                        {
                            Id = 3,
                            BoardId = 1,
                            CreatedAt = new DateTime(2026, 2, 4, 18, 23, 16, 312, DateTimeKind.Utc).AddTicks(527),
                            Description = "Create Angular components",
                            DueDate = new DateTime(2026, 2, 11, 18, 23, 16, 312, DateTimeKind.Utc).AddTicks(448),
                            Priority = 1,
                            Status = 0,
                            Title = "Build UI Components",
                            UpdatedAt = new DateTime(2026, 2, 4, 18, 23, 16, 312, DateTimeKind.Utc).AddTicks(528)
                        },
                        new
                        {
                            Id = 4,
                            BoardId = 2,
                            CreatedAt = new DateTime(2026, 2, 4, 18, 23, 16, 312, DateTimeKind.Utc).AddTicks(530),
                            Description = "Unit and integration tests",
                            Priority = 1,
                            Status = 0,
                            Title = "Write Tests",
                            UpdatedAt = new DateTime(2026, 2, 4, 18, 23, 16, 312, DateTimeKind.Utc).AddTicks(530)
                        });
                });

            modelBuilder.Entity("TaskBoard.Models.TaskItem", b =>
                {
                    b.HasOne("TaskBoard.Models.Board", "Board")
                        .WithMany("Tasks")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Board");
                });

            modelBuilder.Entity("TaskBoard.Models.Board", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
